typelevel/scalacheck

src/main/scala/org/scalacheck/Gen.scala

Update documentation for Gen methods filter, suchThat, retryUntil

---

src/main/scala/org/scalacheck/commands/Commands.scala

In the multi threaded test destroySut was called before the property check was executed

Bug fix for https://github.com/rickynils/scalacheck/issues/138

---

jvm/src/test/scala/org/scalacheck/GenSpecification.scala
src/main/scala/org/scalacheck/Arbitrary.scala
src/main/scala/org/scalacheck/Gen.scala

Took a stab at addressing #215
- Change Arbitrary[Date] to be based on Gen[Calendar]
- Add test for Gen[Calendar]
- Add Arbitrary[Calendar] based on Gen[Calendar]

#215 Target Date edge cases

---

src/main/scala/org/scalacheck/Arbitrary.scala

Although the Unicode spec is clear:
>To ensure that the mapping for a Unicode encoding form is one-to-one, all Unicode scalar values, including those corresponding to noncharacter code points and unassigned code points, must be mapped to unique code unit sequences. Note that this requirement does not extend to high-surrogate and low-surrogate code points, which are excluded by definition from the set of Unicode scalar values.
There is a bug at http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/sun/nio/cs/UnicodeDecoder.java#94 which causes incorrect handling of `'\ufffe'` (which is designated one of those valid "noncharacter code points") in the jdk.  Until they fix the bug by removing that unnecessary test (I submitted a bug report, but it's still pending …

exclude '\uFFFE' from Arbitrary[Char] pending jdk bug review

---

jvm/src/test/scala/org/scalacheck/ShrinkSpecificationJVM.scala
project/plugin.sbt
src/test/scala/org/scalacheck/ShrinkSpecification.scala

add some workarounds for ShrinkSpecification
- https://github.com/rickynils/scalacheck/commit/f1ea446138ccac5a3c0
- https://github.com/rickynils/scalacheck/commit/155a054c61572724508
- https://travis-ci.org/rickynils/scalacheck/builds/106758308

Bump ScalaJS 0.6.8

---

jvm/src/test/scala/org/scalacheck/examples/IntMapSpec.scala

https://github.com/scala/scala/commit/0c5b42d974fbd3703f29f0232e2c9215e41fb379
https://issues.scala-lang.org/browse/SI-9684

use JavaConverters instead of JavaConversions

---

src/main/scala/org/scalacheck/Arbitrary.scala

Previously, the BigDecimal generator could create astronomically-large
numbers that were not safe to use in most tests (so large that working
with them would cause seemingly-infinite hangs). This was primarily
due to using incredibly large scales (e.g. 10^2000000000). In practice
most users of BigDecimal are probably not trying to work with numbers
that large.
This commit also tries to even out the overall distributions of both
BigInt and BigDecimal numbers, while ensuring that none of the values
are so large that they will break most interesting properties. It's
relatively easy for users to write custom generators if they want
extremely large numbers.
Related to #246.

Improve BigInt and BigDecimal generators.

---

src/main/scala/org/scalacheck/Cogen.scala

Fixes #285 (see discussion there).

Use seed.next for Success in Cogen for Try

---

src/main/scala/org/scalacheck/Arbitrary.scala

Added an Arbitrary instance for Function0. This is super simple but I found myself writing it for something and thought it would be good to include so others have it off the shelf.

Arbitrary Function0 Instance

---

LICENSE
js/src/main/scala/org/scalacheck/Platform.scala
jvm/src/main/scala/org/scalacheck/Platform.scala
jvm/src/test/scala/org/scalacheck/ArbitrarySpecification.scala
jvm/src/test/scala/org/scalacheck/GenSpecification.scala
jvm/src/test/scala/org/scalacheck/LazyPropertiesSpecification.scala
jvm/src/test/scala/org/scalacheck/PropertyFilterSpecification.scala
jvm/src/test/scala/org/scalacheck/TestSpecification.scala
jvm/src/test/scala/org/scalacheck/commands/CommandsSpecification.scala
jvm/src/test/scala/org/scalacheck/examples/StringUtils.scala
jvm/src/test/scala/org/scalacheck/rng/SeedSpecification.scala
src/main/scala/org/scalacheck/Arbitrary.scala
src/main/scala/org/scalacheck/Cogen.scala
src/main/scala/org/scalacheck/Gen.scala
src/main/scala/org/scalacheck/Prop.scala
src/main/scala/org/scalacheck/Properties.scala
src/main/scala/org/scalacheck/ScalaCheckFramework.scala
src/main/scala/org/scalacheck/Shrink.scala
src/main/scala/org/scalacheck/Test.scala
src/main/scala/org/scalacheck/commands/Commands.scala
src/main/scala/org/scalacheck/util/Buildable.scala
src/main/scala/org/scalacheck/util/CmdLineParser.scala
src/main/scala/org/scalacheck/util/ConsoleReporter.scala
src/main/scala/org/scalacheck/util/FreqMap.scala
src/main/scala/org/scalacheck/util/Pretty.scala
src/test/scala/org/scalacheck/PropSpecification.scala
src/test/scala/org/scalacheck/ShrinkSpecification.scala
src/test/scala/org/scalacheck/util/BuildableSpecification.scala
src/test/scala/org/scalacheck/util/Pretty.scala

happy new year and thanks for the awesome library!

2016 -> 2017

---

build.sbt
project/plugin.sbt

Maybe some binary compatibility check fail due to https://github.com/rickynils/scalacheck/issues/318

update mima 0.1.14, fix mimaPreviousArtifacts

---

src/test/scala/org/scalacheck/PropSpecification.scala
tools/travis-script.sh

We've been getting build timeouts -- this might help.
A more extreme thing would be to reduce the size ranges under JS,
which I'll do here if this doesn't seem to help.

Do less work on JS under Travis.

---

build.sbt
jvm/src/main/scala/org/scalacheck/Platform.scala
jvm/src/test/scala/org/scalacheck/GenSpecification.scala
jvm/src/test/scala/org/scalacheck/SerializabilitySpecification.scala
jvm/src/test/scala/org/scalacheck/TestSpecification.scala
jvm/src/test/scala/org/scalacheck/examples/StringUtils.scala
src/main/scala/org/scalacheck/Arbitrary.scala
src/main/scala/org/scalacheck/Cogen.scala
src/main/scala/org/scalacheck/Gen.scala
src/main/scala/org/scalacheck/Prop.scala
src/main/scala/org/scalacheck/Shrink.scala
src/main/scala/org/scalacheck/Test.scala
src/main/scala/org/scalacheck/commands/Commands.scala
src/main/scala/org/scalacheck/util/Buildable.scala
src/main/scala/org/scalacheck/util/CmdLineParser.scala
src/main/scala/org/scalacheck/util/ConsoleReporter.scala
src/main/scala/org/scalacheck/util/FreqMap.scala
src/main/scala/org/scalacheck/util/Pretty.scala
src/test/scala/org/scalacheck/PropSpecification.scala
src/test/scala/org/scalacheck/examples/MathSpec.scala

This is a port of @sirthias' PR with *master* merged, to see if Travis will build it cooperatively.
If it passes, then that means we can either merge this PR, or let @sirthias merge *master* to his branch and rebuild. Either way works for me -- I just want to get all these warnings fixed! ;)
Thanks again to Matthias for these fixes.

Sirthias no warnings

---

build.sbt
project/plugin.sbt

Scala.js version bump for 1.12.x

---

js/src/main/scala/org/scalacheck/Platform.scala
jvm/src/main/scala/org/scalacheck/Platform.scala
project/plugin.sbt
src/main/scala/org/scalacheck/Prop.scala
src/main/scala/org/scalacheck/Properties.scala
src/main/scala/org/scalacheck/ScalaCheckFramework.scala

this is for Scala 2.13.0-M1 friendliness; older Scala.js versions
weren't published for 2.13.0-M1

Scala.js version bump for master

---

src/main/scala/org/scalacheck/Arbitrary.scala

Add Arbitrary[UUID]

---

build.sbt
project/plugin.sbt

scala-native 0.3.3 does not support sbt 1.x
fix https://github.com/rickynils/scalacheck/issues/377

update scala-native 0.3.6

---

src/main/scala/org/scalacheck/ScalaCheckFramework.scala

Fixes #185
Tested manually in the Scala build:
```
[success] Total time: 4 s, completed 13/03/2018 1:12:27 PM
> scalacheck/testOnly TreeMapTest
[info] Compiling 1 Scala source to /Users/jz/code/scala/target/scalacheck/test-classes...
[info] + TreeMap.foreach/iterator consistency: OK, passed 100 tests.
[info] + TreeMap.worst-case tree height is iterable: OK, passed 100 tests.
[info] + TreeMap.sorted: OK, passed 100 tests.
[info] + TreeMap.contains all: OK, passed 100 tests.
[info] + TreeMap.size: OK, passed 100 tests.
[info] + TreeMap.toSeq: OK, passed 100 tests.
[info] + TreeMap.head: OK, passed 100 tests.
[info] + TreeMap.last: OK, passed 100 tests.
[info] + TreeMap.head/tail identity: OK, passed 100 tests.
[info] + TreeMap.init/last identity: OK, passed 100 tests.
[info] + TreeMap.take: …
```

Coarser grained tasks for forked SBT mode, fixing failure reporting

---

build.sbt
project/MimaSettings.scala
src/main/scala/org/scalacheck/ScalaCheckFramework.scala

Apparently, MiMa was disabled.

Re-enable mima check

---

src/main/scala/org/scalacheck/Cogen.scala

see https://github.com/rickynils/scalacheck/pull/395#issuecomment-383442015

partially revert #395

---

src/main/scala/org/scalacheck/Arbitrary.scala

Option Arbitrary delegates to Option Gen

---

doc/UserGuide.md

Update user guide to fix #465

---

jvm/src/test/scala/org/scalacheck/ArbitrarySpecification.scala

Add test for recursive Option

---

jvm/src/test/scala/org/scalacheck/GenSpecification.scala
src/main/scala/org/scalacheck/Gen.scala

Gen.posNum should produce reals < 1

---

src/main/scala/org/scalacheck/Prop.scala

Improve docs for deprecating BooleanOperators

---

.travis.yml

Add Coursier cache to Travis

---

build.sbt
project/MimaSettings.scala

Reset the MiMa filters, as well.

Update the mima artifact to 1.14.1

---

build.sbt

Fix Scala.js 1.0 and Scala 2.10 in build

---

build.sbt
examples/commands-leveldb/build.sbt
examples/commands-nix/build.sbt
examples/commands-redis/build.sbt
examples/scalajs/README.md
examples/scalajs/build.sbt
examples/simple-sbt/build.sbt
scalafix/build.sbt

- Bump to 1.14.3
- Update MiMa to 1.14.2
- Update examples. to 1.14.2
- Give more recent snapshot example

Bump version in build post-release

---

.travis.yml
build.sbt

Remove support for 2.10

---

.travis.yml
build.sbt
project/MimaSettings.scala
project/plugin.sbt
src/main/scala-2.13+/org/scalacheck/util/BuildableVersionSpecific.scala
src/main/scala/org/scalacheck/Gen.scala
src/main/scala/org/scalacheck/Prop.scala
src/main/scala/org/scalacheck/util/Pretty.scala
tools/travis-script.sh

Compile in dotty 0.19.0-RC1

---

jvm/src/test/scala/org/scalacheck/SerializabilitySpecification.scala

Add test serialize Arbitrary[List[T]]

---

.travis.yml
build.sbt
project/plugin.sbt
release.sh

Update the 1.14.x branch as part of #586.

Upgrade Scala.js to 1.0.0-RC1

---

CHANGELOG.markdown
RELEASE.markdown
build.sbt

Release notes for 1.14.3

---

.travis.yml
build.sbt
project/plugin.sbt
release.sh

This is for the 1.14.x branch.

Update Scala.js to 1.0.0

---

doc/UserGuide.md
src/test/scala/org/scalacheck/ShrinkSpecification.scala

Use implicit in Shrink.suchThat example

---

jvm/src/test/scala/org/scalacheck/GenSpecification.scala
src/main/scala/org/scalacheck/Gen.scala

Rename Gen.fix to Gen.recursive

---

src/test/scala/org/scalacheck/ShrinkSpecification.scala

Try to improve the readability.

Name cleanup of Shrink tests

---

project/plugin.sbt
release.sh

Update Scala.js 0.6.33 in few more places

---

.travis.yml
build.sbt

Related to #668
@smarter I didn't have to port any changes from the community build, mind taking a look?

bump dotty

---

build.sbt
examples/scalajs/project/plugins.sbt
project/plugin.sbt
release.sh

update Scala.js 1.3.x

---

.travis.yml

Add `dist` and drop `sudo` fields.

Fix travis config warnings

---

build.sbt
project/MimaSettings.scala
src/main/scala/org/scalacheck/Gen.scala

Fixes #696.   Re-enables signature checking in MiMa.

Fix source compatibility 1.15.0

---

jvm/src/test/scala/org/scalacheck/GenSpecification.scala

This is the addendum to the change, proposed in #717, that would have removed the use of `max` function in `Gen.buildableOf` for enforcing collection sizes be zero or more.  ScalaCheck probably only provides _sizes_ between `[0,100]` most of the time, but it turns out users can inject negative values for _size_, via `Gen.resize` for instance, we just didn't have any tests to notice that was the case.

Add tests for Gen.resize

---

src/main/scala/org/scalacheck/Cogen.scala

See #589. This is a copy of #590, which fell through the cracks at some point.

Add Cogen.domainOf (again)

---

.github/workflows/ci.yml
build.sbt
examples/commands-leveldb/build.sbt
examples/commands-nix/build.sbt
examples/commands-redis/build.sbt
examples/commands-redis/src/test/scala/CommandsRedis.scala
examples/scalajs/build.sbt
examples/simple-sbt/build.sbt

Update to Scala 2.13.5

---

build.sbt
examples/commands-leveldb/build.sbt
examples/commands-nix/build.sbt
examples/commands-redis/build.sbt
examples/scalajs/README.md
examples/scalajs/build.sbt
examples/simple-sbt/build.sbt

and use new-style way to say Test

update ScalaCheck version in examples

---

jvm/src/test/scala/org/scalacheck/GenSpecification.scala

Adding coverage while studying change in #778

Add test for Gen.stringOfN

---

.github/workflows/ci.yml
build.sbt
project/plugin.sbt

Drop the sbt-dotty plugin

---

build.sbt
project/MimaSettings.scala

`MimaPlugin` is enabled automatically.

silence MiMa warning

---

jvm/src/test/scala/org/scalacheck/SerializabilitySpecification.scala
project/codegen.scala

Fix serialization of Gen tuples

---

.github/workflows/ci.yml
build.sbt

1.15.4 with Scala 3.0.0 is already out

Scala 3.0.0 final

---

src/main/scala/org/scalacheck/Arbitrary.scala

Improve docs for Arbitrary

---

build.sbt

Will succeed now after mima upgrade in #810.

Enable mima for Scala 3.0 artifact

---

examples/commands-leveldb/build.sbt
examples/commands-nix/build.sbt
examples/commands-redis/build.sbt
examples/scalajs/build.sbt
examples/simple-sbt/build.sbt

Update examples to 3.0.1

---

project/MimaSettings.scala

Remove the filter for a binary change made in #788

Reset the Mima filters to 1.15.4

---

.github/workflows/ci.yml
build.sbt

Enable published snapshots

---

core/shared/src/main/scala/org/scalacheck/Gen.scala

Clarify API documentation of Gen.listOfN.

---

build.sbt

See #1120 for more details about the release.

Prepare for release v1.19.0
