typelevel/scalacheck

- src/main/scala/org/scalacheck/commands/Commands.scala
Sorry, a bug fix for a bug fix: I have originally not seen this case where we have multiple threads but p1 is not successful
> remove sut also in case with multiple threads and if runSeqCmds fails

- src/main/scala/org/scalacheck/Prop.scala
- src/test/scala/org/scalacheck/PropSpecification.scala
This addresses a problem I run into frequently with `Properties` being a mutable map.
``` scala
object Test extends Properties("foo") {
property("bar") = secure {
val c = connectToTheNetwork()
val x = something(c)
c.close()
p(x)
}
}
```
In the above, `connectToTheNetwork()` runs _at object creation time_ (!!!). This can cause all kinds of strange initialization errors and (more frequently) blocked threads. With this PR, you would instead say:
``` scala
object Test extends Properties("foo") {
property("bar") = protect {
val c = connectToTheNetwork
val x = something(c)
c.close()
p(x)
}
}
```
and nothing runs at object creation time, other than the creation of the `Prop` which is completely lazy.
> Added `delay` and `protect` for delaying execution of properties.

- .travis.yml
- build.sbt
- js/src/main/scala/org/scalacheck/Platform.scala
- jvm/src/main/scala/org/scalacheck/Platform.scala
- src/main/scala/org/scalacheck/Test.scala
This fixes the Travis builds, because Node.js is just so much faster and less memory-hungry.
After this PR, you may even want to consider bumping up the number of TESTS to be run in the JS env to something like 100 instead of just 20, because it's so much faster now.
> Run the tests of the JS platform using Node.js instead of Rhino.

- .travis.yml
Some of the scalacheck tests fail with code 137, which usually indicates they're running up against Travis' resource limits. The [new Travis infrastructure] (http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade) provides "...2 dedicated cores and 4GB of memory, vs 1.5 cores and 3GB...", which should alleviate the issue.
> Use Travis Build Containers

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- src/main/scala/org/scalacheck/Gen.scala
This fixes #177 , but I wasn't able to figure out why the position of `Gen.const(null)` has an impact. One thing I noticed is that in the  `Gen.oneOf(Gen.const(null), ....)` case, the sized `Gen` created in `buildableOf` never evaluates `suchThat` with the null value. However, this obviously does occur if the null const is not the first argument. 
Hopefully someone more familiar with the codebase can suggest what the underlying issue is. In the meantime, this patch addresses the simple issue described in the above ticket.
> prevent NPE with Gen.oneOf (#177)

- src/main/scala/org/scalacheck/ScalaCheckFramework.scala
This adds green/red coloring to log output (where supported), making visual test inspection much simpler.
> add colors to console output

- src/main/scala/org/scalacheck/Properties.scala
- src/main/scala/org/scalacheck/Test.scala
This is a basic implementation of the feature request in #187.
This would allow a user to do something like 
```scala
object MyProperties extends Properties("My object") {
override def overrideParams(p: Test.Parameters) = p.withMinSuccessfulTests(20)
}
```
if they want Scalacheck to, for this class only, run 20 tests per property instead of whatever value was specified in the sbt argument or the project default.
> Allow overriding of Test.Parameters in Properties

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- src/main/scala/org/scalacheck/Gen.scala
`Gen.some(g)` is not that much shorter than `g.map(Some.apply)`, but it's a nice parallel to `Gen.option`. Presently we have defined `some` as a convenience function that we use extensively in our scalacheck tests at Twitter.
> Add Gen.some for converting generators to Some(T)

- src/main/scala/org/scalacheck/commands/Commands.scala
Found a small typo: 
```
For an implemtation overview
```
> Fix typo in Commands

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- src/main/scala/org/scalacheck/Gen.scala
A proposed fix for issue #186.
When generating a random double in a range, `chDbl` is calculating max-min, which could potentially be outside of the range of doubles. To prevent this, `chDbl` is just discarding those values, which causes ranges like `Gen.choose(Double.MinValue, Double.MaxValue)` to fail.
As issue #186 says, you're probably better off using `Arbitrary` in this case (they use different generation strategies, and the distribution of doubles produced by `Arbitrary` is probably more useful), but I think it's reasonable to expect `Gen.choose(Double.MinValue, Double.MaxValue)` to generate something.
I've fixed the issue by copying the strategy used in [drmaciver/hypothesis](https://github.com/DRMacIver/hypothesis) for [float …
> Allow Gen.choose to handle a very large range of doubles

- build.sbt
- project/MimaSettings.scala
- project/plugin.sbt
- mima 0.1.6 does not support Scala 2.12.0-M4 https://github.com/typesafehub/migration-manager/issues/78
- fix previous artifact
> fix mima settings

- src/main/scala/org/scalacheck/Cogen.scala
I am not sure it is the best approach, maybe it would be better to use raw methods in jvm world and non raw methods in scala.js. However, I don't know enough about the difference to make the call.
> Replace floatToRawIntBits by floatToIntBits and doubleToRawLongBits by doubleToLongBits

- src/main/scala/org/scalacheck/Prop.scala
- src/main/scala/org/scalacheck/Properties.scala
- src/main/scala/org/scalacheck/ScalaCheckFramework.scala
- src/main/scala/org/scalacheck/Test.scala
An attempt to fix #233 
`Test.parseParams` returns a func `Parameters => Parameters` that applies cmd parameters. It makes possible to have a chain: `default params => coded overwrite => cmd overwrite`
What do you think?
> [Spike] Make coded overrideParameters for Properties possible

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- src/main/scala/org/scalacheck/Gen.scala
- src/main/scala/org/scalacheck/GenArities.scala
- src/main/scala/org/scalacheck/Shrink.scala
- tools/codegen.scala
(This PR is a reworked version of #257. I also tried to reduce the
amount of code churn in this PR, even though there's a lot of code
that I'd like to see reformatted at some point.)
This PR was inspired by #218. It turns out that it ends up being
very easy to accidentally create empty generators (that will never
return Some(_) values) unnecessarily. The particular issue was around
usage of Gen.sized, but there are a number of other combinators that
end up creating empty generators in some cases.
Previously, when the arguments to a combinator make it impossible to
produce a value, ScalaCheck has preferred to produce empty Gen[T]
values. After this change, combinators whose arguments make it
impossible to generate values will instead throw exceptions during
creation. This makes it easier …
> Avoid empty generators when possible (take 2)

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- src/main/scala/org/scalacheck/Gen.scala
* Added the string generators `alphaUpperStr`, `alphaLowerStr` and `alphaNumStr`.
* Changed the order of string generators to match that of the character generators.
* Added tests for `numStr`, `alphaUpperStr`, `alphaLowerStr`, `alphaStr` and `alphaNumStr`.
* Changed `_.forall(c => c.isLetter || c.isDigit)` to `_.forall(_.isLetterOrDigit)` in the definition of `identifier`.
> String generators added.

- jvm/src/test/scala/org/scalacheck/SerializabilitySpecification.scala
- src/main/scala/org/scalacheck/Arbitrary.scala
- src/main/scala/org/scalacheck/Cogen.scala
- src/main/scala/org/scalacheck/Gen.scala
- src/main/scala/org/scalacheck/Prop.scala
- src/main/scala/org/scalacheck/Shrink.scala
- src/main/scala/org/scalacheck/rng/Seed.scala
- src/main/scala/org/scalacheck/util/Buildable.scala
This PR allows `Arbitrary`, `Gen`, `Cogen`, `Shrink` instances, to be `Serializable`, so that these can be used in contexts relying on Java serialization (from closures with Spark in particular).
The unit tests in this PR are far from exhaustive, but illustrate that simple type class instances are indeed serializable.
Note that scalacheck relying on `CanBuildFrom` at some places tends to break serializability by default, as default `CanBuildFrom` instances from the standard library are usually not serializable. To circumvent that, this PR adds a few serializable `CanBuildFrom` instances (in `SerializableCanBuildFroms`) that get implicitly found if `SerializableCanBuildFroms._` is imported.
> Allow type classes to be serializable

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- src/main/scala/org/scalacheck/Gen.scala
This fixes #269. It also includes a (possibly unnecessary) change to
make `Gen.buildableOf` a bit safer, as well as regression tests.
> Fix invalid bounds on `Gen.posNum` (and `Gen.negNum`).

- src/main/scala/org/scalacheck/Arbitrary.scala
This issue came up generating strings for use in Xml; code-point 0xFFFF is for internal use only see http://bit.ly/2cVBrzK. Since the code already excludes the other internal character 0xFFFE it seems to make sense to include this one too.
> 0xFFFF Is also not unicode.

- src/main/scala/org/scalacheck/Shrink.scala
- src/test/scala/org/scalacheck/ShrinkSpecification.scala
This was reported as #244. The root cause was that shrinking certain
values would produce an infinite stream. There were several ways this
could happen -- in the reported case, the fact that Char was unsigned
meant that the strategy of including inverses was able to produce
loops.
The fix was to detect when Integral[T] cannot support negative values,
and disabling negation.
While working on this, I noticed that shrinking floating point
sentinels (i.e. infinities and NaN) would cause a similar issue. I
added code to detect those cases as well.
Fixes #244.
> Fix non-terminating shrink streams.

- src/main/scala/org/scalacheck/Properties.scala
Previously ScalaCheck tried to encode (and return) the number of
failing properties in the exit code. Unfortunately this meant that
multiples of 256 would be seen as having 0 failures.
The new code uses -1 for invalid arguments, 0 for success, and 1 for
one or more failures. The number of failing properties is also printed
explicitly, so that the user can still see this information.
Fixes #240.
> Fix issue where return code could be seen as 0.

- src/main/scala/org/scalacheck/Cogen.scala
It looks like there are issues with implicit resolution for Cogen. See example below. I believe this is related to the contravariance annotation for Cogen and its interaction with limitations in Scala's implicit search (Cogen[Any] is treated as a subtype of Cogen[A] for all A so in searching for the most specific implicit value the compiler infers a type to Any and then has divergence resolving subsequent search for implicit values). I believe this is the reason Ordering is not declared contravariant in the standard library. When I remove the contravariance annotation on Cogen the issue is resolved. All other tests still work with this change.
```
Welcome to Scala 2.12.0-RC1 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_91).
Type in expressions for evaluation. Or try :help.
scala> import …
```
> Make Cogen Invariant

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- src/main/scala/org/scalacheck/Gen.scala
Adds a Gen instance for generating an infinite stream of values given a generator for the type of the underlying values. This is useful for testing that functions designed to be able to handle infinite data structures (e.g. through lazy evaluation) are working correctly. Also includes a new test for this instance. See #280.
> Gen.infiniteStream

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- src/main/scala/org/scalacheck/Gen.scala
Previously retryUntil would throw a StackOverflowException if the
generator failed too many times. It's not obvious to users that the
problem is their generator and/or predicate.
This commit replaces this implicit depth limit with an explicit cutoff
after 10000 tries (along with a custom Exception). It also provides a
two-argument variant of retryUntil that allows the user to specify how
many tries are allowed.
This change should improve the situation in #232.
> Improve retryUntil's behavior during failure.

- jvm/src/test/scala/org/scalacheck/CogenSpecification.scala
- src/main/scala/org/scalacheck/Cogen.scala
This proposal creates a new test suite for Cogen. The tests are based on the concept that Cogen instances should satisfy two properties:
**1. Consistency** - A given Cogen should always return the same output for the same seed and input. In other words, Cogen is referentially transparent.
**2. Uniqueness** - Given a seed, a Cogen should always return different outputs for inputs that are not equal. One can imagine a Cogen that does not do this (e.g. one that is only based on the length of a string to a model a function that only uses that information), but especially for Cogen instances that will generally be available implicitly this seems like a highly desirable property.
With a few minor provisions, all of the existing Cogen instances satisfy these laws. In the case of Function0, …
> CogenSpecification

- jvm/src/test/scala/org/scalacheck/CogenSpecification.scala
- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- src/main/scala/org/scalacheck/Arbitrary.scala
- src/main/scala/org/scalacheck/Cogen.scala
- src/main/scala/org/scalacheck/Gen.scala
- src/main/scala/org/scalacheck/Shrink.scala
- src/test/scala/org/scalacheck/ShrinkSpecification.scala
This adds `Gen`, `Arbitrary`, and `Shrink` instances for both `Duration`
and `FiniteDuration`. It also adds a `Choose` instance for
`FiniteDuration`.
> Add support for Duration and FiniteDuration

- src/main/scala/org/scalacheck/Gen.scala
The idea here is that if you are generating 100 values, it's probably
not that useful for 50 of them to be the same (None). Having a 50%
chance of None is especially problematic when a data structure has
several nested Option fields, in which case it becomes pretty unlikely
that any non-None values are generated for the innermost Option field.
I've arbitrarily chosen a 10% None frequency here, but feel free to
recommend other values that may be better.
> Reduce the frequency of None in Option Gen

- doc/UserGuide.md
- jvm/src/test/scala/org/scalacheck/PropertyFilterSpecification.scala
- src/main/scala/org/scalacheck/ScalaCheckFramework.scala
- src/main/scala/org/scalacheck/Test.scala
- src/main/scala/org/scalacheck/util/CmdLineParser.scala
Allows properties to be filtered based on a supplied criteria. This
allows running of a subset of property tests for a given specification.
The test criteria is specified by the '-f' option.
Eg:
Given the following properties for a String specification:
1. StringProps.String map
2. StringProps.String reverse
when supplied with a "map" criteria, Scalacheck will only run the map property:
1. StringProps.String map
On the commandline:
scala -cp scalacheck.jar:. StringProps -f "map"
Through SBT:
test-only *StringProps -- -f map
The primary motivation for creating this functionality was so that
I could selectively run a subset of properties that were expensive
to run every time. It also helps focus on the current property being
tested without having to run all properties of a specification …
> filter properties based on a criteria

- jvm/src/test/scala/org/scalacheck/LazyPropertiesSpecification.scala
- src/main/scala/org/scalacheck/Prop.scala
- src/main/scala/org/scalacheck/Properties.scala
Fixes #290 by making property registration lazy.
Mima passes against 1.13.1 so this is safe to release in 1.13.4.
Review by @rickynils.
> Fixes #290 (deadlock under 2.12 during property initialization)

- build.sbt
Allows cross versioned execution of tasks without prior
navigation to sub-project.
> Set same cross Scala versions in all (sub)projects

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- src/main/scala/org/scalacheck/Gen.scala
Previously it was possible for the "current system time" to leak
through into generated Calendar instance (and by extention Date
instances). This was especially painful for generated functions (such
as A => Date) where the function is likely to be evaluated at multiple
different system times.
This PR restructures Gen.calendar to ensure that all instances are
initialized from a generated time (in milliseconds). The code is
cleaned up a bit and a test was added to ensure generation is
deterministic.
Fixes #295.
> Make Gen[Calendar] deterministic.

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- src/main/scala/org/scalacheck/Gen.scala
This commit fixes a bug pointed out by @alexarchambault. When
constructing an `A => B` value from `Cogen[A]` and `Gen[B]`, we need
to be able to reliably generate a `B` value given a `Seed`. The
`doPureApply` method was given the ability to retry -- but
unfortunately, it used the same result value (with the same seed)
instead of trying a new one, defeating the retry code.
This commit fixes that problem. It adds tests to ensure that filtered
generators that can also produce real values can be used with
Gen.function1. (If a generator can never produce values it will still
be a problem.)
Fixes #300.
> Fix retrying code in doPureApply.

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- jvm/src/test/scala/org/scalacheck/rng/SeedSpecification.scala
- src/main/scala/org/scalacheck/Gen.scala
- src/main/scala/org/scalacheck/Prop.scala
- src/main/scala/org/scalacheck/Properties.scala
- src/main/scala/org/scalacheck/Test.scala
- src/main/scala/org/scalacheck/rng/Seed.scala
- src/test/scala/org/scalacheck/PropSpecification.scala
This commit adds an `initialSeed` parameter to the Parameter types
that Test and Gen use to control test execution. When set to `None`,
things behave as they usually do, but when set to `Some(seed)`, that
seed will be used to start the execution.
This makes it easier to configure repeatable tests. In the future, you
could imagine ScalaCheck emitting which seed it started with during a
failing test, and providing an interface for re-running the failing
test with the same seed.
Also included are some tests to ensure generators are deterministic.
We can add more of these for different types of generators in the future
as needed.
Review by @rickynils and @sirthias.
> Support deterministic testing using Parameters.

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- src/main/scala/org/scalacheck/Gen.scala
Scalacheck is really great, but it would be nice if I could generate more realistic strings. So I've created 2 new generators for Char and String:
* one for printable characters only
* another for all ASCII characters with weighting on printable characters
Let me know if they seem suitable or need some alteration or better documentation.
> Create ascii generators

- build.sbt
- jvm/src/main/scala/org/scalacheck/Platform.scala
- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- jvm/src/test/scala/org/scalacheck/SerializabilitySpecification.scala
- jvm/src/test/scala/org/scalacheck/TestSpecification.scala
- jvm/src/test/scala/org/scalacheck/examples/StringUtils.scala
- src/main/scala/org/scalacheck/Arbitrary.scala
- src/main/scala/org/scalacheck/Cogen.scala
- src/main/scala/org/scalacheck/Gen.scala
- src/main/scala/org/scalacheck/Prop.scala
- src/main/scala/org/scalacheck/Shrink.scala
- src/main/scala/org/scalacheck/Test.scala
- src/main/scala/org/scalacheck/commands/Commands.scala
- src/main/scala/org/scalacheck/util/Buildable.scala
- src/main/scala/org/scalacheck/util/CmdLineParser.scala
- src/main/scala/org/scalacheck/util/ConsoleReporter.scala
- src/main/scala/org/scalacheck/util/FreqMap.scala
- src/main/scala/org/scalacheck/util/Pretty.scala
- src/test/scala/org/scalacheck/PropSpecification.scala
- src/test/scala/org/scalacheck/examples/MathSpec.scala
In the process of (temporarily) internalizing a sub-set of scalacheck into my project in order to be able to the use the current 1.14 branch I discovered that the current sources produce quite a few compiler warnings that can easily be fixed.
This PR takes these changes upstream.
Most changes don't affect the public API, but in one case they do:
In accordance with `-Ywarn-nullary-unit` the formerly nullary `Test.check` method has now received an empty parameter list.
Since the public API will be broken anyway with 1.14 this change should be ok.
> Enable more compiler warnings, apply respective fixes

- jvm/src/test/scala/org/scalacheck/rng/SeedSpecification.scala
- src/main/scala/org/scalacheck/Properties.scala
- src/main/scala/org/scalacheck/rng/Seed.scala
The major wart this fixes is the return value of fromBase64. This
method now returns Try[Seed], since it is expected to deal with
arbitrary user input.
This commit also improves the string representation of seeds, and
makes the seed internals public (which should be fine, since the seed
is immutable).
Finally this commit includes a few assorted fixes.
> Improve the seed interface a bit.

- build.sbt
With the current warnings on unused imports, the console is almost
unusable. This commit (which mirrors a hack found in Cats) means that
you can use imports again.
> Fix the console.

- build.sbt
- project/plugin.sbt
this is for Scala 2.13.0-M1 friendliness; older Scala.js versions
weren't published for 2.13.0-M1
> Scala.js version bump for 1.13.x

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- src/main/scala/org/scalacheck/Gen.scala
This one-liner should fix the issue in #332 about the distribution of `Gen.pick`.
I've included a unit test in 57b6fb4  that uses `Prop.collect` to show the problem.  However, it's not a unit test worth keeping, IMO.  It's just for showing the problem.  There may be a better test, but it's not the one.  It's not general enough, and it's a bit too noisey:
```
+ Gen.distributed pick: OK, passed 100 tests.
> Collected test data: 
42% 7, 6
25% 7, 5
17% 4, 7
7% 3, 7
4% 7, 2
3% 7, 1
2% 0, 7
```
It shows the distribution gets a lot better with the fix in 2ee295d:
```
+ Gen.distributed pick: OK, passed 100 tests.
> Collected test data: 
7% 6, 1
7% 6, 4
6% 3, 5
6% 5, 2
5% 2, 1
5% 6, 3
5% 0, 4
5% 0, 3
4% 2, 3
4% 0, 1
4% 7, 2
4% 7, 6
3% 6, 2
3% 3, 7
3% 7, 5
3% 4, 3
3% 7, 1
3% 4, 2
3% 4, 1
3% 0, 7
2% …
```
> Gen.pick defect

- .travis.yml
- build.sbt
- project/plugin.sbt
Here is the fix for #349. Also I've upgraded Scala 2.11 to 2.11.11, Scala 2.12 to 2.12.3 and ScalaJS to 0.6.19. 
It looks like there are some new checks for Xlint:unused since Scala 2.12.2. I didn't try to fix all of these errors (there are number of unused parameters and private methods) but just turned these warnings off for Scala >= 2.12.
> Add Scala 2.13.0-M2 suppport

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- src/main/scala/org/scalacheck/Gen.scala
These are two methods I often want with Gen.
I *think* the tailRecM is correct, but I don't know the internal implementation that well so happy to get any feedback on how to improve it.
cc @non
> Add Gen.product and Gen.tailRecM

- .gitignore
- src/main/scala/org/scalacheck/Cogen.scala
It's safe to sort only by the keys, because they are distinct.
Fixes #356
> Drop Ordering bound on the values in cogenMap

- src/main/scala/org/scalacheck/util/ConsoleReporter.scala
- src/main/scala/org/scalacheck/util/Pretty.scala
Relates to this StackOverflow question:
https://stackoverflow.com/questions/30970017/how-to-increase-the-char-column-width-for-the-scalacheck-console-output
I also desired this option, primarily to avoid going nuts when printing a stack trace.
> Support for adjustable-width ConsoleReporter output

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
This was probably a copy-paste error when writing properties so I believe there is no need for much discussion here.
> Fixes the type parameter in a call to arbitrary in a property

- src/main/scala/org/scalacheck/Gen.scala
This method is helpful due to two reasons:
1. Scala standard library monads have this method too. So, as library user, I expect `Gen` to have it.
2. In some cases it's a bit easier to read `filterNot()` invocation compared with `filter`, for example:
```
object Cond { // means condition
def apply(x: Int): Boolean = ???
}
Gen.choose(10, 25).filterNot(Cond) // compare with .filter(!Cond(_))
```
> Add Gen.filterNot() method

- .travis.yml
- build.sbt
- native/src/main/scala/org/scalacheck/Platform.scala
- project/plugin.sbt
- src/test/scala/org/scalacheck/PropSpecification.scala
This builds on top of the original PR #337 by @Duhemm to update to a more recent master. It also includes changes that should make the Travis-CI build pass.
> Updated version of #337: Cross compile to Scala Native

- project/build.properties
- project/plugin.sbt
This pull request updates the build to sbt 1.x; it relies on sbt 1.0.3, which will be published shortly.
Also see:
https://github.com/sbt/sbt-standalone-build/issues/15
https://github.com/sbt/sbt/pull/3669
Please wait for 1.0.3 to be available before merging.
> Bump sbt to 1.0.4, update sbt-pgp

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- src/main/scala/org/scalacheck/Gen.scala
I was able to verify #379 with the following test that checks that there is at least one non-zero value in a sample of three:
```scala
import Double.{NegativeInfinity, PositiveInfinity}
property("choose-infinite-double") = {
Prop.forAllNoShrink(listOfN(3, choose(NegativeInfinity, PositiveInfinity))) { xs =>
xs.exists(_ != 0d)
}
}
```
Here it is failing currently:
[info] ! Gen.choose-infinite-double: Falsified after 0 passed tests.
[info] > ARG_0: List("0.0", "0.0", "0.0")
The test assumes that flipping a `Double.MaxValue`-sided coin and getting a zero three times in a row is impossible.  Someone may need to check my math on that.
scala> 2 * math.pow(Long.MaxValue.toDouble, -3d)
res0: Double = 2.5489470578119236E-57
The fix here just substitutes `Double.MinValue` for …
> Fix Gen.choose for Double infinity

- src/main/scala/org/scalacheck/Cogen.scala
- src/main/scala/org/scalacheck/CogenArities.scala
- tools/codegen.scala
These were changes that were made for fixing errors in a 2.12 milestone and also a fix that avoided breaking binary compatability in 1.13.0 for the bootstrap process.
This reverts #230 it was already partially reverted in 8abd189
> Revert 2.12.0-M4 changes

- build.sbt
Replace with `-Ywarn-unused:-implicits,-explicits`.  Note that `-implicits` was already set.
Currently, building gives a  non-fatal compiler error:
[error] 'params' cannot be negated, it enables other arguments
> Disable -params in 2.12 and later

- build.sbt
It's not possible to hack on Scalacheck from the REPL since #353.
sbt> jvm/console
[info] Starting scala interpreter...
scala> import org.scalacheck.Prop
import org.scalacheck.Prop
<console>:11: warning: Unused import
import org.scalacheck.Prop
^
error: No warnings can be incurred under -Xfatal-warnings.
scala> Prop.passed
<console>:12: error: not found: value Prop
Prop.passed
^
On line 75 of `build.sbt`, this line is supposed to disable it, but the filter is no longer working:
```scala
scalacOptions in (Compile, console) ~= {_.filterNot("-Ywarn-unused-import" == _)},
```
> Fix console scalacOptions

- jvm/src/main/scala/org/scalacheck/Platform.scala
Fixes #406.
This compiles on Java 9, but it doesn't seem there are tests here to verify that this change works.
Seems this code is related to running tests in sbt.  If ScalaCheck's own test suite runs, it may be proof that it works.  Running the debugger and adding a breakpoint, it does appear to be called, for what that's worth.
> Fix compilation on Java 9

- .travis.yml
- build.sbt
> support Scala 2.13.0-M5 (and drop M4)

- doc/UserGuide.md
This renders the exact same on GitHub, but it's friendlier to screen readers and allows linking to (sub)^3-sections.
> Make sub-sub-subsections of the user guide linkable

- src/main/scala/org/scalacheck/Gen.scala
Since commit a2100f6846b047aebc490a48dda49e283b4d2fee, invalid ranges now
throw an error instead of creating empty genererators.
> Fix Scaladoc: choose throws an exception if the range is invalid

- src/main/scala/org/scalacheck/util/Pretty.scala
this is for the Scala community build, where we want to be able
to build everything on JDK 11 to help test Scala
references scala/bug#11125
> work around scala/bug#11125

- build.sbt
- examples/scalajs/project/build.sbt
- project/build.properties
- project/plugin.sbt
@rickynils hopefully this will permit publishing 1.14.0 for Scala.js
on Scala 2.13.0-M5?
> update Scala.js and sbt versions (on 2.13 release branch)

- src/main/scala/org/scalacheck/Arbitrary.scala
Grepcode is dead. openjdk.java.net should be more lasting.
> Update dead link to grepcode

- .travis.yml
Java 11 is out with long-term support.  Adding it to the build adds the build count in Travis from 21 to 31, and the running clock time goes from 30 min to 40 min.
> Add openjdk11 to Travis build

- jvm/src/test/scala/org/scalacheck/examples/StringUtils.scala
Since Java 9, constructor Character in class Character is deprecated.
> use valueOf for construction class Character

- src/main/scala/org/scalacheck/Gen.scala
- src/main/scala/org/scalacheck/Prop.scala
The methods `containerOf`, `containerOfN`, and `nonEmptyContainerOf` all accept two type parameters, not three.
> Fix the scaladocs of Gen.mapOf

- doc/UserGuide.md
- src/main/scala/org/scalacheck/Gen.scala
This is in response to concerns raised about `Gen.pick` in #355.
`Gen.pick`, `Gen.someOf`, and `Gen.atLeastOne` will give a randomly chosen subset of elements, but not in a random order.  This is because `Gen.pick` is implemented with reservoir sampling but without a shuffle operation.  Adding shuffling might be possible, but it could impact performance and would violate the "do one thing well" principle of `Gen.pick`.
For now, just document the situation that results aren't permuted in the User Guide and in the API docs.
> Improve doc for Gen.pick

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- src/main/scala/org/scalacheck/Gen.scala
Hi maintainers,
For convenience, we would like to use the `oneOf` combinator on sets in our tests. So we have widened the argument to `Iterable` from `Seq` and added a test. After merging, the following snippet should compile.
```scala
val set: Set[A] = ???
Gen.oneOf(set)
```
**Background.** Currently, the `oneOf` combinator is restricted to `Seq`. To use sets, there are currently two workarounds. First, we could convert it to a sequence. Second, we could use the `Gen.pick[T]` combinator. The workarounds are shown below.
```scala
val set: Set[A] = ???
// Workaround 1
Gen.oneOf(set.toSeq)
// Workaround 2
Gen.pick(1, set).map(_.head)
```
However, both of these workarounds are inconvenient if the `oneOf` combinator could be widened to accept `Iterable`.
Additionally, we noticed that the …
> Widen "oneOf" argument to "Iterable" from "Seq"

- .travis.yml
- build.sbt
- js/src/main/scala/org/scalacheck/Platform.scala
Resubmission of #459, with a first commit not to use the deprecated `TestUtils` anymore.
> Upgrade to Scala.js 1.0.0-M6.

- .travis.yml
- build.sbt
- js/src/main/scala/org/scalacheck/Platform.scala
Move the build to 2.13.0-RC2 on the 1.14.0 brach.
It may fix the issues with Scala.js 1.0.0-M7, as well, by cherry-picking #460.
> Scala 2.13.0-RC2

- LICENSE
- build.sbt
There is a small modification to BSD 3 clause from [opensource.org](https://opensource.org/licenses/BSD-3-Clause).  There is a mention of EPFL, that was probably a result from originally copying the BSD file from Scala or some or other.
Updated the copyright year in license and updated the license info in the pom file.
> Update license and copyright

- build.sbt
I'm not sure how capable Migration Manager is about finding binary changes with Scala.js artifacts or not, but adding a setting for it at least allows ScalaCheck to publish Scala.js artifacts rather than MiMa needlessly failing.
I tested this, by running the following locally:
```
sbt> ;++2.12.6;js/package
sbt> ;++2.13.0-RC2;js/package
```
Starting sbt with `env SCALAJS_VERSION=1.0.0-M8 sbt`.
This should help with publishing 2.12 and 2.13 artifacts for Scala.js 1.0.0-M8 per #474.
> Fix 1.14.0 MiMa for Scala.js

- .travis.yml
- build.sbt
- examples/scalajs/project/build.sbt
- project/build.properties
- project/plugin.sbt
I verified that the following works locally from sbt:
```
> ++2.13.0
> jvm/package
> js/package
```
That will publish Scala 2.13 and Scalajs 0.6.x for 2.13.
Publishing Scalajs for 1.0.0-M8 for 2.12 and 2.13, also works.  First, start sbt with:
$ env SCALAJS_VERSION=1.0.0-M8 sbt
Then:
```
> ++2.12.6
> js/package
> ++2.13.0
> js/package
```
May require #475 for publish to work, though.
> Publish Scala 2.13.0 for 1.14.0

- CODE_OF_CONDUCT.md
Typelevel is [switching to the Scala Code of Conduct](https://typelevel.org/blog/2019/05/01/typelevel-switches-to-scala-code-of-conduct.html), and encourages all member projects to adopt it.
> Add the Scala Code of Conduct

- src/main/scala/org/scalacheck/commands/Commands.scala
This should fix #447.
Remaining questions:
* why does this fix the issue?!
* if I wanted to write a test for this, how would I go about it?
> Fix shrinking of failed test cases in Commands

- build.sbt
- src/test/scala/org/scalacheck/ShrinkSpecification.scala
This removes -deprecation warnings for 2.13 (since there are over 100
of them). It also tries to make it a bit easier to see which options
are used for which versions. Finally it removes an unused import.
I did this as an isolated PR because it's small and easy to review.
> Clean up warnings and scalac options.

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
This is a follow-up to #333.  The test takes 2 from 8 and outputs too much:
```
> Collected test data: 
5% 6, 7
5% 2, 1
4% 4, 5
4% 3, 7
4% 0, 5
4% 6, 2
4% 7, 5
4% 3, 4
4% 4, 2
4% 6, 4
4% 3, 1
4% 5, 1
4% 0, 2
4% 0, 7
4% 7, 4
3% 7, 1
3% 0, 6
3% 5, 6
3% 6, 1
3% 2, 3
3% 2, 7
3% 0, 1
3% 4, 1
3% 5, 3
3% 0, 4
3% 3, 6
3% 5, 2
3% 0, 3
```
As Paul Ford showed in #355, taking 3 from 4 with `Gen.pick` is a sufficient test and only takes 4 lines of output.
> Cleanup test for Gen.pick

- build.sbt
A cherry-picked version of #475 to master branch.
> MiMa setting for Scalajs milestones

- src/main/scala/org/scalacheck/Arbitrary.scala
- src/main/scala/org/scalacheck/Gen.scala
Originally was 9cb731937451bce5367e9f74d9e61ee6beefc6ca.
> Ported over from #409 by @ceedubs.

- src/main/scala/org/scalacheck/util/Pretty.scala
- src/test/scala/org/scalacheck/util/Pretty.scala
The motivation for this is #476. I wanted to ensure we had stronger
tests for Pretty.break before refactoring it, and also thought that
this implementation was a little bit nicer.
This PR includes a test for stack-safety, a test to ensure we never
create lines longer than the maximum allowed, and that we can
reassemble the original string from the output. The old code passed
all of these (apart from the stack safety test which it failed), which
helps give confidence and that the new implementation is equivalent.
It also includes a Scaladoc method to explain what the method does.
Thanks to @GytisZ for reporting the issue and providing an initial PR.
> Stack-safe implementation of Pretty.break.

- src/main/scala/org/scalacheck/Test.scala
Invalid test parameters, or mixing and matching test parameters that conflict raises an error, but it's not clear why.  For example,
```
> jvm/testOnly org.scalacheck.util.PrettySpecification -- -n 200 -x 100
[error] Uncaught exception when running org.scalacheck.util.PrettySpecification: java.lang.IllegalArgumentException: Invalid test parameters
[error] sbt.ForkMain$ForkError: java.lang.IllegalArgumentException: Invalid test parameters
[error] 	at org.scalacheck.Test$.assertParams(Test.scala:225)
[error] 	at org.scalacheck.Test$.check(Test.scala:307)
[error] 	at org.scalacheck.ScalaCheckRunner$$anon$2.executeInternal(ScalaCheckFramework.scala:123)
[error] 	at org.scalacheck.ScalaCheckRunner$$anon$2.$anonfun$execute$11(ScalaCheckFramework.scala:113)
[error] 	at …
```
> Improve errors for test parameters

- .travis.yml
Adriaan has presumably been filtering his notifications
to /dev/ineverlookinhere
> add Seth to Travis-CI notifications

- .travis.yml
Addresses #507 by configuring Travis CI to store .sbt and .ivy2
directories across jobs to make them run faster.
> Adds cache configuration to the Travis CI config file

- .travis.yml
I've opted to stop building Scala.js on JDK11 to avoid increasing the build count.
> Add Scala.js 1.0 back to Travis build

- src/main/scala/org/scalacheck/Cogen.scala
The change to `Cogen.apply` was flagged as a possible binary compatibility issue in #508.
The basis for this change in #403 was because of some ambiguity in Scala 2.12 with `-Xexperimental`.  
However, the dummy implicit didn't ship with 1.14.0, and its absence didn't seem to be an issue.  It seems downstream projects using `Cogen` haven't had an issue after upgrading to 1.14.0: cats, cats-effect, kittens, enumeratum, scalaz.
> Remove Cogen.apply with dummy implicit

- src/main/scala/org/scalacheck/Properties.scala
This copies the current behavior of `propertyWithSeed(..., None)` into `property(...)`
> Always show seed for failing property check

- project/MimaSettings.scala
I predict this was a filter that was added only because the build was incorrectly comparing Scalajs with regular Scala.  Once the configuration was fixed in #482, the filter was no longer necessary.   This resets the Mima settings to empty, except for disabling the MiMa 0.5 signature checking rule.
> Remove invalid filter from MiMa

- .travis.yml
- build.sbt
- project/plugin.sbt
This change allows multiple versions of Scala Native.
> Allow multiple Scala Native versions

- src/main/scala/org/scalacheck/Test.scala
The previous version, `cp`, was private.  I don't think there's a reason to expose this: 
`Test.Parameters.cpy` should be enough of a fluent interface that a copy constructor is unnecessary.
> Test.Parameters.cpy should be private

- src/main/scala/org/scalacheck/Gen.scala
- src/main/scala/org/scalacheck/Prop.scala
- src/test/scala/org/scalacheck/PropSpecification.scala
Here's the basic issue:
When using viewSeed, we need to put an initialSeed in the
Gen.Parameters used to evaluate the Prop, so we can recover
the seed later and display it. So far, so good.
In some cases, we need to "slide" the seed that's embedded
in the parameters, so we don't reuse it. Any time we need
to evaluate several properties and don't want identical
RNG state (which could lead to identical inputs) we need
to slide.
We were missing a "slide" in flatMap -- we were reusing
the same parameters in both cases. Since flatMap was used
to define && (via for-comprehension) that meant that when
you said p0 && p1, you'd use the same seed for both if
viewSeed was set.
Refined's property was unusual, but valid. Basically, one
property had (x >= 0) ==> and one had (x < 0) ==>. So no
single x …
> Fix for #530

- src/main/scala/org/scalacheck/Prop.scala
- src/main/scala/org/scalacheck/Properties.scala
- src/main/scala/org/scalacheck/util/CmdLineParser.scala
- src/main/scala/org/scalacheck/util/ConsoleReporter.scala
This fixes #527 but also switches to `Console.out.println` in a few places, and removes a strange use of `printf` and carriage returns in the `ConsoleReporter`.  I don't entirely grok the latter, but I don't think it serves any purpose.
> Fix output for bad command-line params

- build.sbt
- release.sh
I had to make a few tweaks to build.sbt to get things reliably building for me
in a sustainable way. Once I got that working, I set up a release.sh script
that I can successfully use to cross-build, cross-test, and cross-publish.
The following commands are useful during the release process:
```
./release.sh compile        # build along all axes
./release.sh test           # ensure all tests pass
./release.sh package        # ensure we can package everythign
./release.sh publishSigned  # actually publish a signed release
```
Note that to publish you currently have to (temporarily) modify build.sbt to
change a few variables. You also have to log into Sonatype to close/publish the
release (assuming all its checks pass).
> Set up a repeatable release process.

- .gitignore
- examples/simple-sbt/project/build.properties
First pass at getting rid of extraneous stuff.
Add missing `build.properties` to simple-sbt example.
> Clean-up the .gitignore file

- project/plugin.sbt
- release.sh
This is the alternative to #549.
> Update Scala.js 0.6.29 in release script

- build.sbt
- release.sh
Hey Erik,
The release script looks sharp.  The only thing I can think of was making the script handle toggling the `isRelease` value.  There's a benefit to the manual step that you had, but it's possible to automate it.  No hard feelings if you want to keep the manual step.
> Auto-set isRelease in release script

- examples/scalajs/README.md
It's not just a snapshot anymore.  The test parameters work, too.
> Update Scala.js example README

- project/plugin.sbt
Since we pass explicit versions in release.sh, it's important to make sure it
doesn't get out of sync with our definitions in plugins.sbt. To that end, this
commit ensures that we get one of two exact versions we're prepared to support.
Otherwise, we'll throw an error during SBT initialization.
This makes it slightly more annoying to test ScalaCheck with a new version of
one of these plugins (you have to modify plugins.sbt as opposed to just passing
a new variable on the command line) but also means we'll never accidentally
release with the wrong version.
I ended up printing before throwing an error because SBT doesn't display the
actual exception (and message) unless you type (l)ast. This way, you'll always
see the message (which should make it pretty obvious what the mistake was).
> Validate ScalaJS and Scala Native versions in plugins.sbt.

- src/main/scala/org/scalacheck/ScalaCheckFramework.scala
I'm not familiar with this portion of the code base, so I'm not sure what the consequence of reverting this, but this change causes Scala.js tests to run again.
> Partial revert of ff83d14

- CHANGELOG.markdown
- RELEASE.markdown
This will likely be the only change in the release.
This is also an opportunity to fix up whitespace/wordwrap in the release notes.
Contributor list pulled with: `git shortlog -ns --no-merges 1.14.1..HEAD`
> Release notes for 1.14.2

- .travis.yml
- build.sbt
Erik pointed out to me that snapshots can be published to Sonatype.  Any interest in re-enabling this?  It may be useful for 1.15 development.  I think it might have been accidentally disabled during Travis cleanup.
Humorously, it was still occuring for just Scala Native:
https://oss.sonatype.org/content/repositories/snapshots/org/scalacheck/scalacheck_native0.3_2.11/
> Re-enable snapshot releases?

- .travis.yml
- build.sbt
- examples/commands-leveldb/build.sbt
- examples/commands-nix/build.sbt
- examples/scalajs/build.sbt
- project/plugin.sbt
- Drop explicit memory settings for JVM
- Only fork JVM in sbt with Scala 2.13
- Switch to Xenial in Travis
- Switch to OpenJDK for Java 8 in Travis
- Update `pomExtra` in sbt to new syntax
- Remove errant `scalacOptions` in `plugins.sbt`.
> Clean up the build

- CHANGELOG.markdown
- src/main/scala/org/scalacheck/Gen.scala
> Force posNum and negNum generators to always return values

- project/codegen.scala
Follow-up to #517.
Even after the change here, the same generated code in `jvm/target/scala-2.13/src_managed` was unchanged.
> Fix indentation of codegen

- .travis.yml
- build.sbt
- jvm/src/test/scala/org/scalacheck/ArbitrarySpecification.scala
- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- jvm/src/test/scala/org/scalacheck/PropertyFilterSpecification.scala
- jvm/src/test/scala/org/scalacheck/ShrinkSpecificationJVM.scala
- jvm/src/test/scala/org/scalacheck/TestSpecification.scala
- jvm/src/test/scala/org/scalacheck/examples/IntMapSpec.scala
- src/main/scala/org/scalacheck/Arbitrary.scala
- src/main/scala/org/scalacheck/Gen.scala
- src/main/scala/org/scalacheck/Shrink.scala
- src/test/scala/org/scalacheck/PropSpecification.scala
- src/test/scala/org/scalacheck/ShrinkSpecification.scala
- src/test/scala/org/scalacheck/examples/Examples.scala
- src/test/scala/org/scalacheck/examples/MathSpec.scala
- src/test/scala/org/scalacheck/util/Pretty.scala
https://dotty.epfl.ch/blog/2019/11/04/20th-dotty-milestone-release.html
- Fix migration warnings:
```
-- Migration Warning: scalacheck/src/main/scala/org/scalacheck/Arbitrary.scala:283:37 
283 |    val undecidedOrPassed = forAll { b: Boolean =>
|                                     ^^^^^^^^^^
|parentheses are required around the parameter of a lambda
```
- Fix whitespace warnings:
```
-- Warning: scalacheck/jvm/src/test/scala/org/scalacheck/PropertyFilterSpecification.scala:73:16 
73 |                prop(pf, propNames, expected)
|                ^
|      Line is indented too far to the right, or a `{' is missing
```
- ~~Fix warnings around `implicitConversions`~~
```
-- Feature Warning: scalacheck/src/main/scala/org/scalacheck/Shrink.scala:250:39 
250 |    else if (skipNegation) q #:: …
```
> Update dotty to 0.20.0-RC1

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
We need to avoid this bug in the future, but could also use tests that combine these aspects of the library.
Follow-up to #568.
> Add tests of Gen.posNum and Gen.listOf

- src/main/scala/org/scalacheck/Gen.scala
> Clean up of Gen

- src/main/scala/org/scalacheck/Arbitrary.scala
> Clean up Arbitrary

- src/main/scala/org/scalacheck/Gen.scala
> Switch to self instead of Gen.this

- src/main/scala/org/scalacheck/Gen.scala
> Change Gen members from def to val

- src/main/scala/org/scalacheck/Gen.scala
- src/main/scala/org/scalacheck/util/Buildable.scala
> Refactor Gen.pick

- .travis.yml
Use a long list of command-line args to JMH so that it just runs once and quickly.
> Add smoke test of benchmarks

- .travis.yml
- examples/scalajs/README.md
- examples/scalajs/build.sbt
- examples/scalajs/project/plugins.sbt
- project/plugin.sbt
- release.sh
Finally Scala.js 1.0.0 has been released https://github.com/scala-js/scala-js/releases/tag/v1.0.0
> Upgrade Scala.js to 1.0.0

- src/main/scala-2.13+/org/scalacheck/ScalaVersionSpecific.scala
- src/main/scala-2.13-/org/scalacheck/ScalaVersionSpecific.scala
- src/main/scala/org/scalacheck/Shrink.scala
This allows to use Shrink from scala 2.13 without getting deprecation
warnings on scala.collection.immutable.Stream
fixes #626
> Adds helper to create Shrink using LazyList

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- src/main/scala/org/scalacheck/Gen.scala
same idea as https://github.com/typelevel/cats/pull/3208 but particular to Gen.
Gen and Parsers are what motivated the 3208 PR.
> Add Gen.fix to make recursive generators cleaner

- doc/UserGuide.md
- src/main/scala/org/scalacheck/Shrink.scala
- src/test/scala/org/scalacheck/ShrinkSpecification.scala
When using `Gen.suchThat` or generators that maintain invariants by construction, shrinking can break those invariants. Add `Shrink.suchThat` to ensure no invalid values are shrunk to.
> Add Shrink.suchThat

- bench/src/main/scala/org/scalacheck/bench/GenBench.scala
- project/codegen.scala
- src/main/scala/org/scalacheck/Gen.scala
- src/main/scala/org/scalacheck/Prop.scala
- src/main/scala/org/scalacheck/util/Buildable.scala
> Refactor of sieve in Gen

- jvm/src/test/scala/org/scalacheck/TestSpecification.scala
- src/main/scala/org/scalacheck/Test.scala
Prevously, the initial seed was used for every single property
evaluation, meaning that even if a property is evaluated 100 times the
same values will be used each time. This is not what users expect, and
makes the library harder to use.
(In particular, the MUnit library hit this bug using Test.check.)
After this commit, the initial seed will be used first, but then a
deterministic set of seeds will be used later. This sequence will be
the same for every run as long as the same number of workers are used.
If the number of workers is changed, the initial seed will be the
same, but the exact sequence of seeds used may differ somewhat.
> Fix a bug with initial seed support.

- src/main/scala/org/scalacheck/Arbitrary.scala
- src/main/scala/org/scalacheck/Gen.scala
> Refactor Char and String generators

- src/main/scala/org/scalacheck/Cogen.scala
Closes #589
I'm not sure about the name. `resultOf` doesn't fit (we're creating `Cogen` for the domain of the function). I'm using `domainOf` for now, but I'm open to suggestions.
I didn't add any tests since this is just sugar over `contramap`.
> Add Cogen.domainOf

- src/main/scala/org/scalacheck/Cogen.scala
Reverts typelevel/scalacheck#590
This PR was apparently targeting the 1.14.x branch, but I think we should merge it into master instead.
@ashawley What do you think? Did you want this targeting 1.14.x?
> Revert "Add Cogen.domainOf"

- src/main/scala/org/scalacheck/util/Pretty.scala
This makes `forAll { (x: Int, y: Int) => false }` fail as follows:
[info] > ARG_0: 0
[info] > ARG_1: 0
[info] > ARG_0_ORIGINAL: -1737265162
[info] > ARG_1_ORIGINAL: -1
instead of
[info] > ARG_0: 0
[info] > ARG_0_ORIGINAL: -1737265162
[info] > ARG_1: 0
[info] > ARG_1_ORIGINAL: -1
I prefer the former error message: when a property fails, I typically
want to see a set of inputs that made it fail.  The new layout shows
me first the shrunk set of inputs (with nothing else interleaved),
then the original set of inputs (with nothing else interleaved).
> Print shrunk values first, then the _ORIGINAL values

- jvm/src/test/scala/org/scalacheck/StatSpecification.scala
- src/main/scala/org/scalacheck/Gen.scala
This commit adds support for several statistical distributions:
- Gaussian (normal)
- Exponential
- Geometric
- Poisson
- Binomial
These distributions are likely to be useful for writing generators, as
well as for fine-grained control of numerical ranges.
Currently, authors using Gen.choose have to decide whether to forbid
testing with large Double values (by using a small range), or to allow
large values (in which case their test will be dominated by large
values). One solution is to use distributions where large values are
possible but rare, such as an exponential distribution.
Similarly, authors can use a geometric distribution to generate the
size of a collection which is usually small, but may occasionally be
large.
> Add various statistical distributions to Gen.

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- src/main/scala/org/scalacheck/Gen.scala
- src/main/scala/org/scalacheck/rng/Seed.scala
This is my partial implementation of Choose[BigInt], as we discussed on Friday (#631). I'd like some feedback before I proceed with BigDecimal.
One major issue. The new property check does not seem to be executing with `sbt test`. This can be verified by replacing the `chooseBigInt.choose()` method with `???` and observing that all of the tests still pass. Any ideas?
> Add choose[BigInt]

- project/MimaSettings.scala
- src/main/scala/org/scalacheck/Prop.scala
dbaeb80e5f1e2aad36a647f4fe55fcfde9d1153e broke binary compatibility by
making `BooleanOperators` private, this does not match the plan discussed
in #540:
> The 1.15.x series will preserve binary-compatibility with 1.14.0 but
is expected to break source-compatibility (e.g. removing the implicit
keyword from some definitions)
This commit implements that: BooleanOperators is public again but is
also made non-implicit.
> Restore binary compatibility with 1.14.0

- jvm/src/test/scala/org/scalacheck/rng/SeedSpecification.scala
- src/main/scala/org/scalacheck/rng/Seed.scala
Seed(0, 0, 0, 0) would always produce the same next value
> Fail Seed with (0, 0, 0, 0)

- src/main/scala/org/scalacheck/Properties.scala
- src/test/scala/org/scalacheck/NoPropertyNestingSpecification.scala
Prevent nesting properties or otherwise adding properties
during execution.
> Prevent nesting properties

- build.sbt
- examples/scalajs/README.md
- examples/simple-sbt/build.sbt
- scalafix/build.sbt
- tools/travis-script.sh
this syntax is more pleasant and is considered standard now
> sbt: use slash syntax throughout build.sbt

- src/main/scala/org/scalacheck/Prop.scala
- src/test/scala/org/scalacheck/PropSpecification.scala
In support of #421, this PR deprecates the single-argument `Prop.collect`.   The method collects statistics on the _parameter_ to a property test.  It conflicts with the second version of `Prop.collect` that takes two arguments, a value and a property.   The two overloaded methods confuse the Scala compiler for two reasons 1) because the former accepts an implicit second argument and 2) because collections from the standard library typically extend `PartialFunction`.
> Deprecate overloaded Prop.collect

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- src/main/scala/org/scalacheck/Gen.scala
In addition to implicit Choose instances for scala.math.BigDecimal and
java.math.BigDecimal we also include explicit constructor methods, since users
may wish to be explicit about the scale they want. We may want to put those
methods directly on Gen, currently the ergonomics of using this are a bit bad:
Gen.Choose.chooseBigDecimalScale(100).choose(0, 1)
The BigDecimal generation is not yet tested. That will also be added in a
follow up. This also optimizes the BigInt generator a bit and generalizes it to
java.math.BigInteger to support that as well.
Addresses #631, #637, and #664
> Add choose methods for both Java and Scala BigDecimal.

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- src/main/scala/org/scalacheck/Gen.scala
Previously, when called with generators Gen.pick could return collections of
any length, when the API promises that they are length `n`.
// should only generate Seq(0,1), Seq(0,2), or Seq(1,2).
val g = Gen.pick(2, Gen.const(0), Gen.const(1), Gen.const(2))
We didn't have a test for this variant of Gen, which explains why we didn't
detect this breakage.
> Fix Gen.pick when used with Gen[_] arguments.

- src/main/scala/org/scalacheck/Gen.scala
Previously we used the standard buildableOf and just filtered out empty
collections. However, given that the underlying methods support a size
parameter it's just as easy to inline buildableOf's implementation and
start the minimum size at 1, not 0.
Fixes #708
> Avoid filtering in nonEmptyBuildableOf.

- .github/workflows/ci.yml
- build.sbt
I've also released 1.15.1 against SJS1 with these changes.
> Support for DottyJS

- jvm/src/test/scala/org/scalacheck/rng/SeedSpecification.scala
While looking at the test failure of #710, I came across this line in the test.  Is there a reason not to test the full entropy of the `Seed.long`?  Maybe constraining only the bottom 31 bits is intended?
> Test the distribution of full long in seed

- src/main/scala/org/scalacheck/commands/Commands.scala
Example output:
```
[info] > Labels of failing property:
[info] Initial State:
[info]   0
[info] Sequential Commands:
[info]    1. TakeNumber => 1
[info]    2. TakeNumber => 2
[info]    3. TakeNumber => 3
[info] Parallel Commands (starting in state = 3)
[info]    1. TakeNumber => 4
[info]    2. TakeNumber => 5
[info]    3. TakeNumber => 7
[info]
[info]    1. TakeNumber => 6
[info]    2. TakeNumber => 7
[info] ARG_0: ...
[info] ARG_0_ORIGINAL: ...
```
(Here "..." is an abberivation.)
> Make printing of Commands failures more readable

- native/src/main/scala/org/scalacheck/Platform.scala
- tools/travis-script.sh
Patch to #751 to make it compile, it still crashes due to reflective instantiation of the test classes.
<details>
<summary>Stack trace</summary>
[error] scala.scalanative.testinterface.common.RPCCore$RPCException: java.lang.Exception: loadable module not found: org.scalacheck.NoPropertyNestingSpecification
[error]         at scala.scalanative.testinterface.common.RPCCore.$anonfun$handleMessage$4(RPCCore.scala:66)
[error]         at scala.Option.foreach(Option.scala:407)
[error]         at scala.scalanative.testinterface.common.RPCCore.$anonfun$handleMessage$1(RPCCore.scala:64)
[error]         at scala.scalanative.testinterface.common.RPCCore.$anonfun$handleMessage$1$adapted(RPCCore.scala:43)
[error]         at scala.scalanative.testinterface.common.Serializer$.withInputStream(Serializer.sc …
> Scala Native 0.4.0

- jvm/src/test/scala/org/scalacheck/CogenSpecification.scala
- src/main/scala/org/scalacheck/Cogen.scala
We already have an `Arbitrary` instance for it and it is really nice to have the `Cogen` instance for law checking with Discipline.
> Add Cogen Instance For UUID

- jvm/src/main/scala/org/scalacheck/time/JavaTimeChoose.scala
- jvm/src/test/scala/org/scalacheck/time/GenSpecification.scala
The minimum value of nanoseconds for both Duration and Instant should be 0, unless the second value == the minimum bound's second value. It was incorrectly encoded as 1.
Fixes #762
> Fix Off By One Error In JavaTimeChoose

- jvm/src/test/scala/org/scalacheck/ArbitrarySpecification.scala
- src/main/scala/org/scalacheck/Arbitrary.scala
Fixes #243.
Quoted symbol is deprecated in Scala 2.13, but the Symbol class is still available.
> Add Arbitrary[Symbol]

- project/MimaSettings.scala
- src/main/scala/org/scalacheck/util/Buildable.scala
- src/test/scala/scala/StringSpecification.scala
> Hide ambiguous implicit buildableSeq

- src/main/scala/org/scalacheck/util/Pretty.scala
Don't pretty-print by default, only when verbosity is 2 or higher.
In SBT, this would be accomplished with:
> testOnly org.scalacheck.PropSpecification -- -v2
Proofs that are run a against large value currently flood the screen or take a long time to run.
> Verbosity level for pretty-printing proofs

- src/main/scala/org/scalacheck/Prop.scala
- src/test/scala/org/scalacheck/PropSpecification.scala
Revert the refactoring done to Prop.all and Prop.atLeastOne in #531.
Fixes #748.
> Fix stack overflow with Prop.all

- tools/travis-script.sh
Turns out those extra quotes didn't do what we thought they would.
> fix CI build script

- build.sbt
- src/main/scala/org/scalacheck/Gen.scala
> Add docs for Gen

- .github/workflows/ci.yml
- build.sbt
Pare down the build.  It's not necessary to run across Scala versions.  
Running against the latest Scala is what we did in the old Travis build, see #609.
> Only run bench once in the build

- build.sbt
Saw this in the Native build and not sure what it does.  
```scala
Compile / doc := (jvm / Compile / doc).value
```
Maybe it used to do something, but is no longer necessary?
> Drop doc setting in native

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
As discussed in #778, users probably do not give a negative to `Gen.stringOf` via `Gen.resize`, but it is allowed so we should capture the behavior in the test suite.
> Add test for Gen.stringOf

- jvm/src/test/scala/org/scalacheck/ChooseSpecification.scala
Continuing from #781, more property name changes,  and use the new checkChoose method more.
> Further cleanup of ChooseSpecification

- README.markdown
Making the Discord support channel more visible by adding a badge with a badge that links to #scalacheck and that never expires :)
This is how it looks like:
> Adds Discord badge

- build.sbt
Set PVP to avoid false negatives, as pointed out by @julienrf.
> ScalaCheck follows semver since 1.14.x

- jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- src/main/scala/org/scalacheck/Arbitrary.scala
- src/main/scala/org/scalacheck/Gen.scala
- src/main/scala/org/scalacheck/Properties.scala
- src/main/scala/org/scalacheck/commands/Commands.scala
- src/test/scala/org/scalacheck/NoPropertyNestingSpecification.scala
- src/test/scala/org/scalacheck/ShrinkSpecification.scala
These are syntax changes that Scala 3.0 suggests when setting `-source:future`.  
There are a lot more suggestions, but these are the ones we can entertain without breaking 2.12 and 2.13 builds.
> Scala 3.0 syntax nits

- README.markdown
This PR adds a badge to the README showing which versions of the artifact support what versions of Scala. At the time of writing, the badge says:
```
scalacheck 1.15.4 (Scala 3.x, 2.13, 2.12), 1.15.2 (Scala 2.11), 1.14.3 (Scala 2.10)
```
[![scalacheck Scala version support](https://index.scala-lang.org/typelevel/scalacheck/scalacheck/latest-by-scala-version.svg)](https://index.scala-lang.org/typelevel/scalacheck/scalacheck)
More details on the badge format here: https://github.com/scalacenter/scaladex/pull/660
> Add badge to README showing supported versions of Scala

- jvm/src/main/scala/org/scalacheck/time/JavaTimeArbitrary.scala
Caused a very narrow range of inputs in some tests I was writing 😄
> Fix Arbitrary[Year] instance max value

- jvm/src/test/scala/org/scalacheck/SerializabilitySpecification.scala
Follow-up to #796 for a more robust check of Java serialization.
> Check roundtrip in serialize tests

- .github/workflows/ci.yml
- build.sbt
- examples/commands-leveldb/build.sbt
- examples/commands-nix/build.sbt
- examples/commands-redis/build.sbt
- examples/scalajs/build.sbt
- examples/simple-sbt/build.sbt
> Add Scala 3.1.0 to build

- .github/workflows/ci.yml
- build.sbt
Bumps Scala 3 to 3.1.x and Scalacheck to 1.16.x. Closes https://github.com/typelevel/scalacheck/issues/878. Supersedes https://github.com/typelevel/scalacheck/pull/868.
> Onwards and upwards

- CHANGELOG.markdown
Closes https://github.com/typelevel/scalacheck/issues/886.
I guess I should have PRed the release notes directly here instead of opening an issue, but anyway.
> Update Changelog for v1.16.0

- core/jvm/src/test/scala/org/scalacheck/commands/CommandsSpecification.scala
- core/shared/src/main/scala/org/scalacheck/commands/Commands.scala
Fixes #893
`for (Some(v) <- Map(...).values) yield v` would throw MatchError as soon as it tries to process a value that doesn't conform to Some(v).
The tests didn't detect this because `property("...") = rhs` was re-evaluating `rhs` each time the property is evaluated, which means that Commands.property() only ran one evaluation at a time (so `suts` would always be empty when we run those for comprehensions).
> [Commands] Fix MatchError when using multiple workers

- core/shared/src/main/scala/org/scalacheck/Prop.scala
- core/shared/src/test/scala/org/scalacheck/PropSpecification.scala
This is a proposal to change the way `Prop` is running the shrinking process, which I think can mitigate #129.
Currently, when scalacheck finds an input that either proves that the property is false or throws an exception it start the shrinking process and find the first input in the list which cause any failure.
My proposal is to change that so that we find the first input in the list which cause **the same failure status as before** (meaning an `Exception` with the same class or a `False`).
Motivation
-----------
The current behaviour might be confusing because scalacheck finds an error and can hide it behind some other error after shrinking. 
As a nice side effect it will mitigate #129 (shrinking disregards any filters on an explicit Gen). This actually what I find more interesting …
> Keep the same error type while shrinking

- core/shared/src/main/scala/org/scalacheck/Prop.scala
- core/shared/src/test/scala/org/scalacheck/PropSpecification.scala
This fixes the problem introduced by #838 reported in #909. 
The collect I introduced in my previous PR matched on nothing instead of saving the original exception type. As a consequence the the shrink process reads the whole stream provided by the shrinker. I imagine on a shrink with a very long stream (or infinite, but not sure if that exists in the wild) it would just hang.
cc @armanbilge
> fix wrong match in shrinker (fixes #909)

- core/jvm/src/test/scala/org/scalacheck/TestSpecification.scala
- core/shared/src/main/scala/org/scalacheck/Test.scala
(re-attempt of #841, after that was inadvertently turned into an empty PR in the process of moving to a feature branch in my fork)
A `Prop.forAll` of multiple parameters will use the initial seed to generate the first parameter and slide the seed once for each of the subsequent parameters.  When combined with `Test.check` which slides the seed before evaluating the property, this means that for a property with _m_ > 1 parameters, if the _i_ th evaluation of the property had seeds (seed1 ... seedm), then the _i_+1 th evaluation will have seeds (seed2 ... seedm, seedm.slide).  If the same generator is used for multiple parameters, then a generated value in one evaluation will be reused in a different position in a specific later evaluation.
This addresses this by varying the number of …
> Deterministically vary the number of seed slides in Test.check

- doc/UserGuide.md
User guide examples have few compilation errors when using Scala 3. For instance [here](https://github.com/typelevel/scalacheck/blob/main/doc/UserGuide.md?plain=1#L89):
```
[error]   |  val propReverseList = forAll { l: List[String] => l.reverse.reverse == l }
[error]   |                                                 ^
[error]   |parentheses are required around the parameter of a lambda
[error]   |This construct can be rewritten automatically under -rewrite -source 3.0-migration.
```
According to [Scala 3 migration guide](https://docs.scala-lang.org/scala3/guides/migration/incompat-syntactic.html#parentheses-around-lambda-parameter)
> When followed by its type, the parameter of a lambda is now required to be enclosed in parentheses.
This PR fixes those errors
> fix scala 3 compilation errors in user guide examples

- bench/src/main/scala/org/scalacheck/bench/GenBench.scala
- core/js/src/main/scala/org/scalacheck/Platform.scala
- core/jvm/src/main/scala/org/scalacheck/Platform.scala
- core/jvm/src/test/scala/org/scalacheck/ChooseSpecification.scala
- core/jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- core/jvm/src/test/scala/org/scalacheck/LazyPropertiesSpecification.scala
- core/jvm/src/test/scala/org/scalacheck/SerializabilitySpecification.scala
- core/jvm/src/test/scala/org/scalacheck/TestSpecification.scala
- core/jvm/src/test/scala/org/scalacheck/commands/CommandsShrinkSpecification.scala
- core/native/src/main/scala/org/scalacheck/Platform.scala
- core/shared/src/main/scala/org/scalacheck/Arbitrary.scala
- core/shared/src/main/scala/org/scalacheck/Cogen.scala
- core/shared/src/main/scala/org/scalacheck/Gen.scala
- core/shared/src/main/scala/org/scalacheck/Prop.scala
- core/shared/src/main/scala/org/scalacheck/Properties.scala
- core/shared/src/main/scala/org/scalacheck/ScalaCheckFramework.scala
- core/shared/src/main/scala/org/scalacheck/Shrink.scala
- core/shared/src/main/scala/org/scalacheck/Test.scala
- core/shared/src/main/scala/org/scalacheck/commands/Commands.scala
- core/shared/src/main/scala/org/scalacheck/rng/Seed.scala
- core/shared/src/main/scala/org/scalacheck/util/Pretty.scala
- core/shared/src/test/scala/org/scalacheck/PropSpecification.scala
- core/shared/src/test/scala/org/scalacheck/util/BuildableSpecification.scala
- core/shared/src/test/scala/org/scalacheck/util/PrettySpecification.scala
- core/shared/src/test/scala/scala/StringSpecification.scala
This is by no means all of them, but it is many of them, especially the very benign ones such as unused parameters.
There are a few more involved changes, such as deprecating a few methods and adding a few replacements. For example,
* The new `check_` methods in `Test`.
* The `with` methods in the `trait R` type.
> Fix Many Of The Warnings

- core/jvm/src/test/scala/org/scalacheck/CogenSpecification.scala
- core/shared/src/main/scala/org/scalacheck/Cogen.scala
This commit also updates the Map and Set instances to proxy to the SortedMap and SortedSet instances as they already required sorting the Map/Set in order to yield a consistent iteration of the underlying structure.
> Add Cogen instances for SortedSet and SortedMap

- core/jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- core/shared/src/main/scala/org/scalacheck/Gen.scala
I totally realize that there are a lot of other ways to achieve the same functionality with the existing generators,
but I think it is a quite basic feature and can come handy when someone (me, personally) just needs to "grab and go" a non-empty string. So I believe it would complement the `nonEmptyListOf` and `nonEmptyMap` generators pretty well.
> Add Gen.nonEmptyStringOf

- core/shared/src/main/scala/org/scalacheck/Gen.scala
> add a comment line about `nonEmptyStringOf`

- core/shared/src/main/scala/org/scalacheck/Properties.scala
When extending `Properties` in a Scala 3 code base one currently has to use `scala.language.adhocExtensions`. 
According to the documentation `Properties` is clearly intended for extension.
> Add `open` to `Properties` to prevent Scala 3 compile errors

- core/shared/src/main/scala/org/scalacheck/ScalaCheckFramework.scala
- core/shared/src/main/scala/org/scalacheck/Test.scala
- core/shared/src/main/scala/org/scalacheck/util/Buildable.scala
prepare Scala 2.13.12
- https://github.com/scala/scala/pull/10439
> add explicit type

- .scalafmt.conf
- bench/src/main/scala/org/scalacheck/bench/GenBench.scala
- core/jvm/src/test/scala/org/scalacheck/ChooseSpecification.scala
- core/jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- core/jvm/src/test/scala/org/scalacheck/ShrinkSpecificationJVM.scala
- core/shared/src/main/scala-2.12-/org/scalacheck/util/BuildableVersionSpecific.scala
- core/shared/src/main/scala-2.13+/org/scalacheck/util/BuildableVersionSpecific.scala
- core/shared/src/main/scala/org/scalacheck/Arbitrary.scala
- core/shared/src/main/scala/org/scalacheck/Gen.scala
- core/shared/src/main/scala/org/scalacheck/Prop.scala
- core/shared/src/main/scala/org/scalacheck/Properties.scala
- core/shared/src/main/scala/org/scalacheck/Shrink.scala
- core/shared/src/main/scala/org/scalacheck/Test.scala
- core/shared/src/main/scala/org/scalacheck/commands/Commands.scala
- core/shared/src/main/scala/org/scalacheck/rng/Seed.scala
- core/shared/src/main/scala/org/scalacheck/time/JavaTimeArbitrary.scala
- core/shared/src/main/scala/org/scalacheck/time/JavaTimeChoose.scala
- core/shared/src/main/scala/org/scalacheck/util/CmdLineParser.scala
- core/shared/src/main/scala/org/scalacheck/util/ConsoleReporter.scala
- core/shared/src/main/scala/org/scalacheck/util/Pretty.scala
- core/shared/src/test/scala-2.12-/org/scalacheck/time/OrderingVersionSpecific.scala
- core/shared/src/test/scala-2.13+/org/scalacheck/time/OrderingVersionSpecific.scala
Prefer the Scaladoc comment format used by Scala 3.
The two-space "gutter" makes it easier to read the source text. (Users of IDEs and published API will be indifferent to the source.)
It doesn't appear that the matter received any discussion last summer.
> Prefer docstrings.style = AsteriskSpace

- core/shared/src/main/scala-2.12-/org/scalacheck/util/BuildableVersionSpecific.scala
- core/shared/src/main/scala-2.13+/org/scalacheck/util/BuildableVersionSpecific.scala
- core/shared/src/main/scala/org/scalacheck/util/Buildable.scala
- core/shared/src/test/scala/org/scalacheck/util/BuildableSpecification.scala
- doc/UserGuide.md
As `java.util.ArrayList` is supported in `containerOf`, introduce builder to generate `java.util.HashMap` from tuple generator.
The doc states `java.util.ArrayList` is supported by default, but the implicit evidence `evt: C[T] => Traversable[T]` is missing. Adding it in `BuildableVersionSpecific`.
Add new instances in `BuildableSpecification` to verify compile ability.
> Add buildable for java.util.HashMap

- core/jvm/src/test/scala/org/scalacheck/GenSpecification.scala
- project/codegen.scala
Adds a code generator for `Gen.zipWith` functions.
Example:
```scala
case class Foo(pos: Int, ascii: String, hex: String)
Gen.zipWith(Gen.posNum[Int], Gen.asciiStr, Gen.hexStr)(Foo.apply)
```
Without `Gen.zipWith` the same was possible to accomplish with `Gen.zip`, however it would required an additional `map` over an intermediary tuple instance:
```scala
Gen.zip(Gen.posNum[Int], Gen.asciiStr, Gen.hexStr)
.map { case (pos, ascii, hex) => Foo(pos, ascii, hex)) }
```
Therefore `Gen.zipWith` allows to avoid the intermediate conversion which can come in handy in come cases.
Note that `Gen.zipWith` starts with arity 2 whereas `Gen.zip` starts with arity 1.
However, I think the latter was an oversight – `Gen.zip` for arity 1 is a no-op function.
> Introduce `Gen.zipWith` multi-arity method

- core/jvm/src/test/scala/org/scalacheck/ScalaCheckFrameworkSpecification.scala
- core/shared/src/main/scala/org/scalacheck/ScalaCheckFramework.scala
Previously, ScalaCheck ignored the selectors that it receives as input in the "root task". This prevented users from running only a subset of properties in a specification by passing their `TestSelector` to ScalaCheck in a `TaskDef`.
This patch fixes this by having the root task program the execution of only the requested properties if the `TaskDef` contains only `TestSelector`s. ScalaCheck's behavior remains unchanged if the `TaskDef` contains any other kind of `Selector`.
> Verify only props matching the given TestSelectors
